name: Build
on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - "**.md"
  push:
    branches:
      - main
    paths-ignore:
      - "**.md"
  schedule:
    - cron: "0 0 * * *" # daily at midnight

jobs:
  plugin_test:
    name: asdf plugin test
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        cli-version: ['1.6.0']
    runs-on: ${{ matrix.os }}
    steps:
      - name: asdf_plugin_test
        uses: asdf-vm/actions/plugin-test@v1
        with:
          command: cfssl version
          version: ${{ matrix.cli-version }}